### ISSUE TITLE
[Tracker] Gitbook Docs

### ISSUE THREAD

**Issue by XavierChanth** [atsign-foundation/docs#1]
```[tasklist]
### Tasks
- [ ] https://github.com/atsign-foundation/docs/issues/2
- [ ] https://github.com/atsign-foundation/docs/issues/3
- [ ] https://github.com/atsign-foundation/docs/issues/4
- [ ] https://github.com/atsign-foundation/docs/issues/6
```

**Comment by xavierchanth** [comment]
I will be focusing on docs in the next Sprint, so I gave it 8SP
