### ISSUE TITLE
Solutions pages

### ISSUE THREAD

**Issue by XavierChanth** [atsign-foundation/docs#2]
Solutions pages for each of the following, explaining:
- What it does
- What it's used for
- How to install
- Usage

```[tasklist]
### Tasks
- [ ] https://github.com/atsign-foundation/docs/issues/5
- [ ] Iot Deployments page
- [ ] Control plane / RPC page
- [ ] atmospherePro page
```
